"""
skill_call.py — Deep Coding Skill Example
==========================================
Shows how the Hermes agent calls the deep_coding skill.

The agent preprocesses the raw user request with Grok 4.3,
then forwards the optimized problem to Claude via deep_coding.py.

Usage:
    python skill_call.py "Build a PyTorch CNN for MNIST and export to ONNX"
    python skill_call.py "Complex architecture task" --heavy
"""

import asyncio
import sys
from deep_coding import deep_code, format_cost_report


async def run_deep_coding(user_request: str, heavy: bool = False) -> None:
    """
    Simulates how Agent calls the deep_coding skill.

    In production, `optimized_problem` is generated by the Hermes agent
    (Grok preprocesses the raw user request before forwarding to Claude).
    Here we pass the request directly for demonstration purposes.
    """
    print(f"📨 User request: {user_request}")
    print(f"🔄 Mode: {'HEAVY — Claude Fable 5' if heavy else 'Standard — Claude Opus 4.8'}")
    print("=" * 60)

    # In production: Hermes Agent (Grok) preprocesses and optimizes the prompt here.
    # For this demo we pass the request directly.
    optimized_problem = user_request

    result = await deep_code(problem=optimized_problem, heavy=heavy)

    print(result["result"])
    print("\n" + "=" * 60)
    print("💰 Cost Report")
    print(format_cost_report(result))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python skill_call.py '<problem>' [--heavy]")
        sys.exit(0)

    request  = sys.argv[1]
    use_heavy = len(sys.argv) > 2 and sys.argv[2] == "--heavy"

    asyncio.run(run_deep_coding(request, heavy=use_heavy))